pipeline {
    agent any

    environment {
        // NHN Cloud NCR 정보
        NCR_REGISTRY = "4a7e3ac9-kr1-registry.container.nhncloud.com"
        NCR_NAMESPACE = "ncr_test"
        NCR_IMAGE_NAME = "myapp"
        NCR_TAG = "latest"
        NCR_CREDENTIALS_ID = "NCR_CREDENTIALS"

        // GitHub Repository 정보
        GIT_REPO_URL = "https://github.com/jihun2189/kubernetes-anotherclass-sprint2.git"
        GIT_BRANCH = "main"
    }
    
    stages {
        stage('Checkout Source Code from GitHub') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO_URL}"
            }
        }

        stage('Build Application') {
            steps {
                script {
                    sh """
                    chmod +x ./gradlew
                    ./gradlew clean build
                    """
                }
            }
        }

        stage('Prepare Docker Build Context') {
            steps {
                script {
                    sh """
                    cp build/libs/app-0.0.1-SNAPSHOT.jar 2121/build/docker/
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                    docker build -t \${NCR_REGISTRY}/\${NCR_NAMESPACE}/\${NCR_IMAGE_NAME}:\${NCR_TAG} \
                    -f 2121/build/docker/Dockerfile 2121/build/docker/
                    """
                }
            }
        }

        stage('Login to NHN Cloud NCR') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: NCR_CREDENTIALS_ID, usernameVariable: 'NCR_USER', passwordVariable: 'NCR_PASS')]) {
                        sh """
                        echo "\${NCR_PASS}" | docker login \${NCR_REGISTRY} -u "\${NCR_USER}" --password-stdin
                        """
                    }
                }
            }
        }

        stage('Push Docker Image to NHN Cloud NCR') {
            steps {
                script {
                    sh """
                    docker push \${NCR_REGISTRY}/\${NCR_NAMESPACE}/\${NCR_IMAGE_NAME}:\${NCR_TAG}
                    """
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    sh """
                    docker rmi \${NCR_REGISTRY}/\${NCR_NAMESPACE}/\${NCR_IMAGE_NAME}:\${NCR_TAG}
                    """
                }
            }
        }
    }
}
